// openeebus_unity.c — placeholder only
// The actual openeebus C sources are compiled via individual oe__*.c wrapper
// files generated by _generate_unity_build() in __init__.py on each compile.
// Each wrapper includes exactly one source file as its own translation unit.
